/**
 * ╔══════════════════════════════════════════════════════════════════════╗
 * ║  BANK PYTAŃ MATURALNYCH — EDYTUJ WŁAŚNIE TEN PLIK                 ║
 * ╚══════════════════════════════════════════════════════════════════════╝
 *
 * To jest główne miejsce do ręcznej edycji zadań maturalnych.
 * Każde zadanie ma jawnie opisane:
 *   - typ: "zamkniete" albo "otwarte"
 *   - poziom: 3 = ZAAWANSOWANE (zadania maturalne nie spadają niżej)
 *   - pytanie: treść zadania
 *   - wskazowka: podpowiedź widoczna po kliknięciu „Podpowiedź”
 *   - rozwiazanie: pełne rozwiązanie/uzasadnienie po sprawdzeniu
 *   - wzor: najważniejsza zależność, jeśli występuje
 *
 * Dla zamkniętego:
 *   odpowiedzi: { A: "...", B: "...", C: "...", D: "..." }
 *   poprawna: "A" / "B" / "C" / "D"
 *
 * Dla otwartego:
 *   odpowiedzWzorcowa: krótka odpowiedź referencyjna
 *   slowaKluczowe: słowa/fragmenty, które pomagają automatycznie ocenić odpowiedź
 *
 * Możesz zmieniać treść pytań bez ruszania script.js.
 * Poziom 3 oznacza ZAAWANSOWANE. Każde pytanie może mieć własną podpowiedź i rozwiązanie.
 * Dodatkowe pola organizacyjne: dzial, podtemat, lekcja — aplikacja uzupełnia je automatycznie.
 * Nie zmieniaj nazw pól technicznych. Możesz swobodnie zmieniać treść.
 */

const BANK_PYTAN_MATURALNYCH = {
  termodynamika: [
    {id:"TER-01",typ:"zamkniete",poziom:3,pytanie:"Do 0,20 kg wody o temperaturze 80°C dolano 0,30 kg wody o temperaturze 20°C. Pomijając straty ciepła, jaka będzie temperatura końcowa mieszaniny?",odpowiedzi:{A: "44°C", B: "50°C", C: "56°C", D: "62°C"},poprawna:"A",wzor:"m₁c(T₁−T)=m₂c(T−T₂)",wskazowka:"Ponieważ jest to ta sama substancja, ciepło właściwe skraca się. Zapisz bilans energii: ciepło oddane przez cieplejszą wodę = ciepło pobrane przez chłodniejszą.",rozwiazanie:"0,20(80−T)=0,30(T−20). Stąd 16−0,20T=0,30T−6, więc T=44°C."},
    {id:"TER-02",typ:"zamkniete",poziom:3,pytanie:"Gaz doskonały znajduje się w sztywnym zbiorniku. Jego temperatura rośnie z 300 K do 450 K, a początkowe ciśnienie wynosi 100 kPa. Jakie jest ciśnienie końcowe?",odpowiedzi:{A: "125 kPa", B: "200 kPa", C: "67 kPa", D: "150 kPa"},poprawna:"D",wzor:"p/T=const",wskazowka:"Stała objętość oznacza przemianę izochoryczną. Porównaj ilorazy p/T dla obu stanów.",rozwiazanie:"p₂=p₁T₂/T₁=100·450/300 kPa=150 kPa."},
    {id:"TER-03",typ:"zamkniete",poziom:3,pytanie:"Silnik cieplny pobiera ze źródła 2,4 kJ energii, a do chłodnicy oddaje 1,5 kJ. Jaka jest jego sprawność?",odpowiedzi:{A: "60%", B: "90%", C: "37,5%", D: "62,5%"},poprawna:"C",wzor:"η=(Q_h−Q_c)/Q_h",wskazowka:"Praca użyteczna jest różnicą między ciepłem pobranym i oddanym. Dopiero tę pracę podziel przez ciepło pobrane ze źródła.",rozwiazanie:"W=2,4−1,5=0,9 kJ. η=0,9/2,4=0,375=37,5%."},
    {id:"TER-04",typ:"zamkniete",poziom:3,pytanie:"Gaz zostaje sprężony adiabatycznie. Zewnętrzna siła wykonuje nad gazem pracę 420 J. Jak zmienia się energia wewnętrzna gazu, jeśli pomijamy zmianę energii kinetycznej i potencjalnej?",odpowiedzi:{A: "Rośnie o 210 J", B: "Rośnie o 420 J", C: "Maleje o 420 J", D: "Nie zmienia się"},poprawna:"B",wzor:"ΔU=Q+W_{nad gazem}",wskazowka:"Adiabatycznie oznacza Q=0. Zwróć uwagę, że praca jest wykonywana nad gazem, a nie przez gaz.",rozwiazanie:"ΔU=0+420 J=+420 J, więc energia wewnętrzna rośnie."},
    {id:"TER-05",typ:"zamkniete",poziom:3,pytanie:"Lód o masie 0,15 kg w temperaturze 0°C całkowicie topnieje. Przyjmij ciepło topnienia lodu L=334 kJ/kg. Ile energii trzeba dostarczyć?",odpowiedzi:{A: "50,1 kJ", B: "223 kJ", C: "334 kJ", D: "5,01 kJ"},poprawna:"A",wzor:"Q=mL",wskazowka:"Podczas topnienia w temperaturze 0°C energia nie ogrzewa lodu, lecz zmienia jego stan skupienia. Użyj ciepła topnienia.",rozwiazanie:"Q=0,15·334 kJ=50,1 kJ."},
    {id:"TER-06",typ:"zamkniete",poziom:3,pytanie:"Idealny gaz wykonuje cykl, w którym po całym cyklu wraca do stanu początkowego. Co musi być prawdziwe dla zmiany energii wewnętrznej po pełnym cyklu?",odpowiedzi:{A: "ΔU>0", B: "Zależy wyłącznie od pracy wykonanej w cyklu", C: "ΔU=0", D: "ΔU<0"},poprawna:"C",wskazowka:"Energia wewnętrzna jest funkcją stanu. Po powrocie do tego samego stanu jej wartość jest taka sama.",rozwiazanie:"Po pełnym cyklu stan początkowy i końcowy są identyczne, więc ΔU=0."},
    {id:"TER-07",typ:"zamkniete",poziom:3,pytanie:"W izolowanym kalorymetrze metalowy element o masie 0,40 kg i temperaturze 120°C zanurzono w 0,20 kg wody o temperaturze 20°C. Ciepło właściwe metalu wynosi 900 J/(kg·K), wody 4200 J/(kg·K). Jaka temperatura ustali się w przybliżeniu?",odpowiedzi:{A: "72,0°C", B: "45,0°C", C: "60,0°C", D: "90,0°C"},poprawna:"B",wzor:"m_m c_m(T_m−T)=m_w c_w(T−T_w)",wskazowka:"Zrównaj energię oddaną przez metal z energią pobraną przez wodę. Nie zakładaj średniej arytmetycznej temperatur.",rozwiazanie:"0,4·900(120−T)=0,2·4200(T−20). Po rozwiązaniu T≈45°C."},
    {id:"TER-08",typ:"zamkniete",poziom:3,pytanie:"Gaz doskonały ma stałą temperaturę. Jego objętość zmniejszono z 6,0 dm³ do 2,0 dm³, a początkowe ciśnienie wynosiło 90 kPa. Jakie będzie ciśnienie końcowe?",odpowiedzi:{A: "810 kPa", B: "30 kPa", C: "180 kPa", D: "270 kPa"},poprawna:"D",wzor:"p₁V₁=p₂V₂",wskazowka:"To przemiana izotermiczna. Iloczyn pV pozostaje stały.",rozwiazanie:"p₂=90·6/2=270 kPa."},
    {id:"TER-09",typ:"otwarte",poziom:3,pytanie:"Czajnik o mocy 2,0 kW ogrzewa 1,5 kg wody od 20°C do 100°C. Przyjmij c=4200 J/(kg·K). Oblicz minimalny czas ogrzewania i podaj wynik w sekundach.",odpowiedzWzorcowa:"252 s",poprawnaWartosc:252,tolerancja:0.005,jednostka:"s",wymagaJednostki:true,slowaKluczowe:["252","sek"],wskazowka:"Najpierw policz Q=mcΔT, a następnie skorzystaj z P=Q/t. Nie uwzględniaj strat, bo pytanie dotyczy czasu minimalnego.",wzor:"Q=mcΔT, P=Q/t",rozwiazanie:"Q=1,5·4200·80=504000 J. t=Q/P=504000/2000=252 s."},
    {id:"TER-10",typ:"otwarte",poziom:3,pytanie:"Gaz doskonały przechodzi ze stanu A: p=100 kPa, V=2,0 L, T=300 K do stanu B: V=3,0 L, T=450 K. Wyznacz ciśnienie w stanie B.",odpowiedzWzorcowa:"100 kPa",poprawnaWartosc:100,tolerancja:0.005,jednostka:"kPa",wymagaJednostki:true,slowaKluczowe:["100","kPa"],wskazowka:"Porównaj oba stany równaniem pV/T=const. Uważaj, aby objętości były w tych samych jednostkach.",wzor:"p₁V₁/T₁=p₂V₂/T₂",rozwiazanie:"p₂=p₁V₁T₂/(T₁V₂)=100·2·450/(300·3)=100 kPa."},
    {id:"TER-11",typ:"otwarte",poziom:3,pytanie:"Urządzenie pobiera 900 kJ ciepła i wykonuje pracę 250 kJ na otoczeniu. Oblicz zmianę jego energii wewnętrznej.",odpowiedzWzorcowa:"650 kJ",poprawnaWartosc:650,tolerancja:0.005,jednostka:"kJ",wymagaJednostki:true,slowaKluczowe:["650","kJ"],wskazowka:"Ustal konwencję znaku: praca wykonana przez układ zmniejsza jego energię wewnętrzną. Zastosuj pierwszą zasadę termodynamiki.",wzor:"ΔU=Q−W",rozwiazanie:"ΔU=900−250=650 kJ."},
    {id:"TER-12",typ:"otwarte",poziom:3,pytanie:"Dlaczego podczas wrzenia wody przy stałym ciśnieniu temperatura wody nie rośnie mimo dalszego dostarczania energii? Odpowiedz, odwołując się do energii wewnętrznej.",odpowiedzWzorcowa:"Energia jest zużywana na zmianę stanu skupienia, a nie na wzrost średniej energii kinetycznej cząsteczek.",slowaKluczowe:["zmian","stanu","energia","kinetycz"],wskazowka:"Rozdziel energię związaną z ruchem cieplnym cząsteczek od energii potrzebnej do pokonania oddziaływań między nimi.",wzor:"Q=mL",rozwiazanie:"Podczas wrzenia dostarczana energia zwiększa energię potencjalną oddziaływań między cząsteczkami i umożliwia przejście cieczy w gaz. Średnia energia kinetyczna, a więc temperatura, pozostaje stała przy stałym ciśnieniu."}
  ],
  mechanika: [
    {id:"MECH-01",typ:"zamkniete",poziom:3,pytanie:"Samochód o masie 1200 kg jedzie z 20 m/s i hamuje ze stałym opóźnieniem 5 m/s². Jaką drogę pokona do zatrzymania?",odpowiedzi:{A: "40 m", B: "20 m", C: "80 m", D: "100 m"},poprawna:"A",wzor:"v²=v₀²+2as",wskazowka:"Przy końcowej prędkości v=0. Nie musisz wyznaczać czasu; użyj zależności łączącej prędkość, przyspieszenie i drogę.",rozwiazanie:"0=20²−2·5·s, więc s=40 m."},
    {id:"MECH-02",typ:"zamkniete",poziom:3,pytanie:"Klocek 4 kg zsuwa się po równi o kącie 30°. Współczynnik tarcia kinetycznego wynosi 0,20, g=10 m/s². Jakie jest przyspieszenie klocka w dół równi?",odpowiedzi:{A: "5,00 m/s²", B: "1,73 m/s²", C: "7,00 m/s²", D: "3,27 m/s²"},poprawna:"D",wzor:"a=g(sinα−μcosα)",wskazowka:"Rozłóż ciężar na składową wzdłuż równi i prostopadłą. Tarcie ma wartość μN i działa przeciwnie do ruchu.",rozwiazanie:"a=10(0,5−0,20·0,866)≈3,27 m/s²."},
    {id:"MECH-03",typ:"zamkniete",poziom:3,pytanie:"Pocisk o masie 20 g porusza się z prędkością 300 m/s i wbija się w nieruchomy klocek 1,48 kg. Po zderzeniu poruszają się razem. Jaka jest prędkość układu?",odpowiedzi:{A: "60 m/s", B: "300 m/s", C: "4,0 m/s", D: "6,0 m/s"},poprawna:"C",wzor:"m₁v₁=(m₁+m₂)v",wskazowka:"Zderzenie jest doskonale nieelastyczne, więc zachowuje się pęd, ale nie energia kinetyczna. Zamień 20 g na kilogramy.",rozwiazanie:"0,020·300=(1,50)v, więc v=4,0 m/s."},
    {id:"MECH-04",typ:"zamkniete",poziom:3,pytanie:"Ciało porusza się po okręgu o promieniu 0,80 m z prędkością 4,0 m/s. Jaka siła dośrodkowa działa na ciało o masie 0,50 kg?",odpowiedzi:{A: "1,6 N", B: "10 N", C: "2,5 N", D: "6,4 N"},poprawna:"B",wzor:"F_d=mv²/r",wskazowka:"Siła dośrodkowa nie jest nowym rodzajem siły; jest wypadkową skierowaną do środka. Oblicz jej wartość z mv²/r.",rozwiazanie:"F=0,5·16/0,8=10 N."},
    {id:"MECH-05",typ:"zamkniete",poziom:3,pytanie:"Jednorodny pręt o długości 2 m i masie 6 kg może obracać się wokół osi przechodzącej przez jego środek. Jaki jest jego moment bezwładności względem tej osi?",odpowiedzi:{A: "2 kg·m²", B: "12 kg·m²", C: "1 kg·m²", D: "8 kg·m²"},poprawna:"A",wzor:"I=1/12 mL²",wskazowka:"Dla jednorodnego pręta obracanego wokół osi przez środek obowiązuje konkretny wzór na moment bezwładności.",rozwiazanie:"I=(1/12)·6·2²=2 kg·m²."},
    {id:"MECH-06",typ:"zamkniete",poziom:3,pytanie:"Kamień rzucono poziomo z wysokości 45 m z prędkością 12 m/s. Przyjmij g=10 m/s² i pomiń opór. Jaką wartość będzie miała jego prędkość tuż przed uderzeniem?",odpowiedzi:{A: "≈21,0 m/s", B: "≈12,0 m/s", C: "≈32,3 m/s", D: "≈45,0 m/s"},poprawna:"C",wzor:"v²=v_x²+v_y², v_y²=2gh",wskazowka:"Składowa pozioma pozostaje równa 12 m/s. Najpierw wyznacz pionową składową prędkości z wysokości, a na końcu złóż składowe wektorowo.",rozwiazanie:"v_y=√(2·10·45)=30 m/s. v=√(12²+30²)=√1044≈32,3 m/s."},
    {id:"MECH-07",typ:"zamkniete",poziom:3,pytanie:"Sprężyna o stałej 250 N/m jest ściśnięta o 0,12 m. Jaką maksymalną prędkość uzyska klocek 0,50 kg, jeśli cała energia sprężystości przejdzie w energię kinetyczną?",odpowiedzi:{A: "3,46 m/s", B: "2,68 m/s", C: "1,34 m/s", D: "5,37 m/s"},poprawna:"B",wzor:"1/2kx²=1/2mv²",wskazowka:"Porównaj energie, a następnie skróć czynnik 1/2. Nie potrzebujesz czasu działania siły.",rozwiazanie:"v=x√(k/m)=0,12√(250/0,50)≈2,68 m/s."},
    {id:"MECH-08",typ:"zamkniete",poziom:3,pytanie:"Dwa satelity mają tę samą masę i krążą po orbitach kołowych wokół Ziemi. Promień orbity drugiego jest czterokrotnie większy. Ile razy dłuższy jest jego okres obiegu?",odpowiedzi:{A: "2 razy", B: "4 razy", C: "16 razy", D: "8 razy"},poprawna:"D",wzor:"T²∝r³",wskazowka:"Skorzystaj z III prawa Keplera. Stosunek okresów otrzymasz po spierwiastkowaniu sześcianu stosunku promieni.",rozwiazanie:"T₂/T₁=(r₂/r₁)^(3/2)=4^(3/2)=8."},
    {id:"MECH-09",typ:"otwarte",poziom:3,pytanie:"Piłkę rzucono pionowo w górę z prędkością 20 m/s. Przyjmij g=10 m/s². Oblicz maksymalną wysokość ponad punkt wyrzutu.",odpowiedzWzorcowa:"20 m",poprawnaWartosc:20,tolerancja:0.005,jednostka:"m",wymagaJednostki:true,slowaKluczowe:["20","m"],wskazowka:"W najwyższym punkcie prędkość wynosi zero. Zastosuj zależność bez czasu albo bilans energii.",wzor:"v²=v₀²−2gh",rozwiazanie:"0=20²−2·10·h, więc h=20 m."},
    {id:"MECH-10",typ:"otwarte",poziom:3,pytanie:"Na poziomej powierzchni klocek 2 kg jest ciągnięty poziomo siłą 10 N. Współczynnik tarcia kinetycznego wynosi 0,25, g=10 m/s². Oblicz pracę wypadkowej siły po przesunięciu o 5 m.",odpowiedzWzorcowa:"25 J",poprawnaWartosc:25,tolerancja:0.005,jednostka:"J",wymagaJednostki:true,slowaKluczowe:["25","J"],wskazowka:"Najpierw oblicz tarcie i siłę wypadkową. Następnie pomnóż siłę wypadkową przez przesunięcie.",wzor:"F_w=F−μmg, W_w=F_w s",rozwiazanie:"T=0,25·2·10=5 N. F_w=10−5=5 N. W=5·5=25 J."},
    {id:"MECH-11",typ:"otwarte",poziom:3,pytanie:"Pojazd o masie 1000 kg zwiększa prędkość z 10 m/s do 20 m/s. Oblicz przyrost jego energii kinetycznej.",odpowiedzWzorcowa:"150 kJ",poprawnaWartosc:150,tolerancja:0.005,jednostka:"kJ",wymagaJednostki:true,slowaKluczowe:["150","kJ"],wskazowka:"Policz energię kinetyczną w obu stanach i odejmij wartość początkową od końcowej.",wzor:"E_k=1/2mv²",rozwiazanie:"ΔE=1/2·1000(20²−10²)=500·300=150000 J=150 kJ."},
    {id:"MECH-12",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij, dlaczego podczas zderzenia doskonale nieelastycznego zachowanie energii kinetycznej nie jest zasadą zachowania, mimo że zachowany jest pęd.",odpowiedzWzorcowa:"Część energii kinetycznej przechodzi w energię wewnętrzną, odkształcenia i inne formy energii, ale całkowita energia oraz pęd układu są zachowane.",slowaKluczowe:["energia","wewnętrz","odkształ","pęd","zachowan"],wskazowka:"Rozróżnij zasadę zachowania pędu od bilansu całkowitej energii. Zastanów się, co dzieje się z energią podczas odkształcenia ciał.",rozwiazanie:"W zderzeniu nieelastycznym część początkowej energii kinetycznej zamienia się m.in. w energię wewnętrzną i energię odkształceń. Całkowita energia jest zachowana, podobnie jak pęd izolowanego układu."}
  ],
  grawitacja_astronomia: [
    {id:"GRA-01",typ:"zamkniete",poziom:3,pytanie:"Satelita porusza się po orbicie kołowej o promieniu 4R, podczas gdy drugi o tej samej masie po orbicie R. Jak zmienia się jego prędkość orbitalna?",odpowiedzi:{A: "Jest dwukrotnie mniejsza", B: "Jest czterokrotnie mniejsza", C: "Jest dwukrotnie większa", D: "Nie zmienia się"},poprawna:"A",wzor:"v=√(GM/r)",wskazowka:"Prędkość orbitalna zależy od odwrotności pierwiastka z promienia. Podstaw stosunek 4R/R.",rozwiazanie:"v₂/v₁=√(R/4R)=1/2."},
    {id:"GRA-02",typ:"zamkniete",poziom:3,pytanie:"Jeśli promień orbity kołowej satelity zwiększymy dziewięciokrotnie, jego okres obiegu zmieni się...",odpowiedzi:{A: "9-krotnie", B: "3-krotnie", C: "81-krotnie", D: "27-krotnie"},poprawna:"D",wzor:"T²∝r³",wskazowka:"Z III prawa Keplera wynika T∝r^(3/2). Policz 9^(3/2).",rozwiazanie:"T₂/T₁=9^(3/2)=27."},
    {id:"GRA-03",typ:"zamkniete",poziom:3,pytanie:"Dwa ciała znajdują się w odległości r. Jeśli odległość zwiększymy trzykrotnie, siła grawitacji między nimi...",odpowiedzi:{A: "Wzrośnie 9 razy", B: "Nie zmieni się", C: "Zmniejszy się 9 razy", D: "Zmniejszy się 3 razy"},poprawna:"C",wzor:"F=GMm/r²",wskazowka:"Odległość występuje w mianowniku w drugiej potędze.",rozwiazanie:"F₂/F₁=(r₁/r₂)²=(1/3)²=1/9."},
    {id:"GRA-04",typ:"zamkniete",poziom:3,pytanie:"Satelita na orbicie kołowej ma energię mechaniczną E<0. Co oznacza znak ujemny?",odpowiedzi:{A: "Grawitacja nie wykonuje pracy", B: "Układ jest związany grawitacyjnie i nie ma wystarczającej energii do ucieczki do nieskończoności", C: "Satelita porusza się z ujemną prędkością", D: "Energia kinetyczna jest ujemna"},poprawna:"B",wzor:"E=−GMm/(2r)",wskazowka:"W polu grawitacyjnym poziom zero energii potencjalnej przyjmuje się w nieskończoności. Energia ujemna oznacza stan związany.",rozwiazanie:"Dla orbity kołowej E=−GMm/(2r)<0, więc satelita jest związany z ciałem centralnym."},
    {id:"GRA-05",typ:"zamkniete",poziom:3,pytanie:"Planeta krąży po orbicie eliptycznej. W punkcie najbliższym gwieździe ma największą prędkość. Która zasada najlepiej wyjaśnia ten fakt?",odpowiedzi:{A: "Zachowanie momentu pędu", B: "Zachowanie ładunku", C: "Prawo Ohma", D: "Prawo Archimedesa"},poprawna:"A",wzor:"L=mrv_⊥=const",wskazowka:"Siła grawitacji jest siłą centralną, więc moment siły względem środka jest zerowy. Rozważ zachowanie momentu pędu.",rozwiazanie:"Brak momentu zewnętrznego względem środka oznacza zachowanie momentu pędu. Przy mniejszym r prędkość poprzeczna musi wzrosnąć."},
    {id:"GRA-06",typ:"zamkniete",poziom:3,pytanie:"Prędkość ucieczki z powierzchni planety zależy od jej masy M i promienia R. Która zależność jest poprawna?",odpowiedzi:{A: "v_u=GM/R", B: "v_u=2GM/R²", C: "v_u=√(2GM/R)", D: "v_u=√(GM·R)"},poprawna:"C",wzor:"1/2mv²−GMm/R=0",wskazowka:"Zastosuj zasadę zachowania energii, przyjmując, że w nieskończoności prędkość graniczna wynosi zero.",rozwiazanie:"1/2mv²=GMm/R, więc v=√(2GM/R)."},
    {id:"GRA-07",typ:"zamkniete",poziom:3,pytanie:"Widmo galaktyki jest przesunięte ku czerwieni. Najbardziej naturalnym wnioskiem jest, że galaktyka...",odpowiedzi:{A: "Nie ma ruchu względem obserwatora", B: "Oddala się od obserwatora", C: "Zbliża się do obserwatora", D: "Ma niższą temperaturę bez związku z ruchem"},poprawna:"B",wzor:"z≈v/c dla v≪c",wskazowka:"Dla efektu Dopplera dla światła przesunięcie ku czerwieni oznacza wzrost obserwowanej długości fali.",rozwiazanie:"Przesunięcie ku czerwieni odpowiada oddalaniu się źródła od obserwatora w przybliżeniu klasycznym."},
    {id:"GRA-08",typ:"zamkniete",poziom:3,pytanie:"Dwa satelity mają tę samą orbitę kołową, ale pierwszy ma masę dwukrotnie większą. Jak zmienia się jego prędkość orbitalna?",odpowiedzi:{A: "Rośnie czterokrotnie", B: "Rośnie dwukrotnie", C: "Maleje dwukrotnie", D: "Nie zmienia się"},poprawna:"D",wzor:"v=√(GM/r)",wskazowka:"Wzór na prędkość orbitalną nie zawiera masy satelity, jeśli jego masa jest pomijalna wobec masy ciała centralnego.",rozwiazanie:"Dla tej samej orbity v=√(GM/r), więc masa satelity nie zmienia prędkości orbitalnej."},
    {id:"GRA-09",typ:"otwarte",poziom:3,pytanie:"Satelita porusza się po orbicie kołowej o promieniu 4R z okresem 8 godzin. Jaki okres będzie miał satelita na orbicie o promieniu R wokół tego samego ciała centralnego?",odpowiedzWzorcowa:"1 godzina",poprawnaWartosc:1,tolerancja:0.005,slowaKluczowe:["1","godzin"],wskazowka:"Zastosuj T∝r^(3/2). Zmniejszenie promienia czterokrotnie zmniejsza okres osiem razy.",wzor:"T²∝r³",rozwiazanie:"T_R/T_4R=(R/4R)^(3/2)=1/8, więc T_R=8 h/8=1 h."},
    {id:"GRA-10",typ:"otwarte",poziom:3,pytanie:"Oblicz przyspieszenie grawitacyjne na wysokości równej promieniowi Ziemi nad jej powierzchnią, jeśli przy powierzchni wynosi g₀=9,8 m/s².",odpowiedzWzorcowa:"2,45 m/s²",poprawnaWartosc:2.45,tolerancja:0.005,jednostka:"m/s²",wymagaJednostki:true,slowaKluczowe:["2,45","m/s"],wskazowka:"Na tej wysokości odległość od środka Ziemi wynosi 2R. Przyspieszenie grawitacyjne maleje jak 1/r².",wzor:"g=GM/r²",rozwiazanie:"g=9,8·(R/2R)²=9,8/4=2,45 m/s²."},
    {id:"GRA-11",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij, dlaczego astronauta na orbicie może odczuwać nieważkość, mimo że nadal działa na niego grawitacja Ziemi.",odpowiedzWzorcowa:"Astronauta i statek są w ciągłym swobodnym spadku po orbicie; grawitacja pełni rolę siły dośrodkowej, więc brak jest siły nacisku podłoża.",slowaKluczowe:["swobodnym spadku","orbicie","grawitacja","dośrodkow"],wskazowka:"Nieważkość nie oznacza braku grawitacji. Zastanów się, co mierzy waga lub siła nacisku podłoża.",rozwiazanie:"Statek i astronauta spadają ku Ziemi z takim samym przyspieszeniem, ale mają prędkość styczną wystarczającą do utrzymywania orbity. Nie ma stałego nacisku podłoża na astronautę, dlatego odczuwa nieważkość."},
    {id:"GRA-12",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij, dlaczego planety poruszają się szybciej w pobliżu Słońca niż w pobliżu aphelium.",odpowiedzWzorcowa:"W pobliżu Słońca odległość od środka jest mniejsza, a zachowanie momentu pędu wymusza większą prędkość poprzeczną.",slowaKluczowe:["momentu pędu","mniejsza","odległość","większą prędkość"],wskazowka:"Siła grawitacji jest centralna. Zapisz zależność dla momentu pędu i porównaj dwa położenia na orbicie.",rozwiazanie:"Ponieważ moment pędu L=mrv_⊥ jest zachowany, przy mniejszym r prędkość poprzeczna musi być większa."}
  ],
  fale_drgania: [
    {id:"FAL-01",typ:"zamkniete",poziom:3,pytanie:"Fala ma długość 0,80 m i częstotliwość 2,5 Hz. Jaką ma prędkość rozchodzenia?",odpowiedzi:{A: "2,0 m/s", B: "3,2 m/s", C: "0,32 m/s", D: "2,5 m/s"},poprawna:"A",wzor:"v=λf",wskazowka:"Prędkość fali jest iloczynem długości fali i częstotliwości.",rozwiazanie:"v=0,80·2,5=2,0 m/s."},
    {id:"FAL-02",typ:"zamkniete",poziom:3,pytanie:"Źródło dźwięku zbliża się do nieruchomego obserwatora. Obserwowana częstotliwość jest większa od emitowanej, ponieważ...",odpowiedzi:{A: "prędkość dźwięku w powietrzu rośnie bez ograniczeń", B: "amplituda automatycznie rośnie", C: "długość fali obserwowanej rośnie", D: "fronty fali docierają do obserwatora częściej"},poprawna:"D",wzor:"f' = f·v/(v−v_s)",wskazowka:"W efekcie Dopplera zmienia się odstęp między kolejnymi frontami fali docierającymi do obserwatora.",rozwiazanie:"Dla źródła zbliżającego się mianownik v−v_s jest mniejszy, więc f'>f."},
    {id:"FAL-03",typ:"zamkniete",poziom:3,pytanie:"Na strunie o długości 1,2 m powstaje fala stojąca z trzema strzałkami (trzema połówkami długości fali). Jaka jest długość fali?",odpowiedzi:{A: "1,20 m", B: "3,60 m", C: "0,80 m", D: "0,40 m"},poprawna:"C",wzor:"L=3λ/2",wskazowka:"Trzy strzałki oznaczają trzy połówki długości fali mieszczące się w długości struny.",rozwiazanie:"1,2=3λ/2, więc λ=0,80 m."},
    {id:"FAL-04",typ:"zamkniete",poziom:3,pytanie:"Dwie fale o tej samej amplitudzie i częstotliwości spotykają się w fazie. Jaki jest efekt interferencji w miejscu nakładania?",odpowiedzi:{A: "Zanik energii obu fal", B: "Maksymalne wzmocnienie", C: "Całkowite wygaszenie", D: "Zmiana częstotliwości na dwukrotnie większą"},poprawna:"B",wzor:"Δφ=2πk",wskazowka:"Fale w fazie mają zgodne wychylenia. Dodaj ich amplitudy w miejscu interferencji.",rozwiazanie:"Dla zgodnej fazy następuje interferencja konstruktywna, a amplituda w idealnym przypadku jest dwukrotnie większa."},
    {id:"FAL-05",typ:"zamkniete",poziom:3,pytanie:"Dwie częstotliwości 256 Hz i 260 Hz są emitowane jednocześnie. Jaką częstotliwość dudnień usłyszy obserwator?",odpowiedzi:{A: "4 Hz", B: "258 Hz", C: "1 Hz", D: "516 Hz"},poprawna:"A",wzor:"f_d=|f₁−f₂|",wskazowka:"Dudnienia wynikają z powolnej zmiany amplitudy, której częstość jest różnicą częstotliwości fal.",rozwiazanie:"f_d=|260−256|=4 Hz."},
    {id:"FAL-06",typ:"zamkniete",poziom:3,pytanie:"Jeśli amplituda drgań harmonicznych zostanie podwojona, a częstotliwość pozostanie stała, maksymalna prędkość drgającego ciała...",odpowiedzi:{A: "nie zmieni się", B: "zmniejszy się dwukrotnie", C: "podwoi się", D: "wzrośnie czterokrotnie"},poprawna:"C",wzor:"v_max=ωA",wskazowka:"Przy stałej częstotliwości ω jest stałe. Zobacz, jak prędkość maksymalna zależy liniowo od amplitudy.",rozwiazanie:"v_max=ωA, więc podwojenie A podwaja v_max."},
    {id:"FAL-07",typ:"zamkniete",poziom:3,pytanie:"W doświadczeniu Younga odległość między prążkami wzrośnie, jeśli...",odpowiedzi:{A: "zmniejszymy odległość ekranu od szczelin", B: "zwiększymy długość fali i pozostawimy geometrię bez zmian", C: "zmniejszymy długość fali", D: "zwiększymy odległość między szczelinami"},poprawna:"B",wzor:"Δx=λL/d",wskazowka:"Odległość prążków jest proporcjonalna do długości fali i odległości ekranu, a odwrotnie proporcjonalna do odległości szczelin.",rozwiazanie:"Δx=λL/d, więc wzrost λ powoduje wzrost odległości prążków."},
    {id:"FAL-08",typ:"zamkniete",poziom:3,pytanie:"W rurze otwartej z obu stron najniższy ton podstawowy ma długość fali równą...",odpowiedzi:{A: "4L", B: "L/2", C: "L", D: "2L"},poprawna:"D",wzor:"L=λ/2",wskazowka:"Dla pierwszej harmonicznej rura otwarta z obu stron zawiera pół długości fali.",rozwiazanie:"L=λ/2, więc λ=2L."},
    {id:"FAL-09",typ:"otwarte",poziom:3,pytanie:"Fala na strunie ma częstotliwość 50 Hz i długość 1,6 m. Oblicz prędkość fali.",odpowiedzWzorcowa:"80 m/s",poprawnaWartosc:80,tolerancja:0.005,jednostka:"m/s",wymagaJednostki:true,slowaKluczowe:["80","m/s"],wskazowka:"Zastosuj podstawową zależność między prędkością, długością fali i częstotliwością.",wzor:"v=λf",rozwiazanie:"v=1,6·50=80 m/s."},
    {id:"FAL-10",typ:"otwarte",poziom:3,pytanie:"Źródło dźwięku o częstotliwości 600 Hz zbliża się do nieruchomego obserwatora z prędkością 30 m/s. Przyjmij prędkość dźwięku 330 m/s. Oblicz częstotliwość obserwowaną.",odpowiedzWzorcowa:"660 Hz",poprawnaWartosc:660,tolerancja:0.005,jednostka:"Hz",wymagaJednostki:true,slowaKluczowe:["660","Hz"],wskazowka:"Dla nieruchomego obserwatora i poruszającego się źródła użyj f'=fv/(v−v_s).",wzor:"f'=fv/(v−v_s)",rozwiazanie:"f'=600·330/(330−30)=660 Hz."},
    {id:"FAL-11",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij, dlaczego w fali stojącej występują węzły, w których wychylenie jest stale równe zero.",odpowiedzWzorcowa:"W węzłach spotykające się fale mają zawsze przeciwne fazy, więc ich wychylenia znoszą się w każdej chwili.",slowaKluczowe:["przeciwne fazy","znoszą","zero","węzł"],wskazowka:"Pomyśl o superpozycji dwóch fal o tej samej amplitudzie poruszających się w przeciwnych kierunkach.",rozwiazanie:"W węzłach różnica faz wynosi π, więc wychylenia dwóch fal są przeciwne i ich suma jest równa zero dla każdej chwili."},
    {id:"FAL-12",typ:"otwarte",poziom:3,pytanie:"W doświadczeniu interferencyjnym zwiększono odległość między szczelinami dwukrotnie. Jak zmieni się odległość między prążkami i dlaczego?",odpowiedzWzorcowa:"Zmniejszy się dwukrotnie, ponieważ Δx=λL/d i odległość między prążkami jest odwrotnie proporcjonalna do d.",slowaKluczowe:["zmniejszy","dwukrotnie","odwrotnie proporcjonalna","d"],wskazowka:"Przekształcanie wzoru nie jest potrzebne. Wystarczy przeanalizować proporcjonalność w równaniu dla prążków.",wzor:"Δx=λL/d",rozwiazanie:"Jeśli d wzrośnie 2 razy, przy stałych λ i L wartość Δx spadnie 2 razy."}
  ],
  optyka: [
    {id:"OPT-01",typ:"zamkniete",poziom:3,pytanie:"Soczewka skupiająca ma ogniskową 10 cm. Przedmiot ustawiono 30 cm od soczewki. W jakiej odległości powstanie obraz rzeczywisty?",odpowiedzi:{A: "15 cm", B: "7,5 cm", C: "20 cm", D: "30 cm"},poprawna:"A",wzor:"1/f=1/x+1/y",wskazowka:"Podstaw f=10 cm i x=30 cm do równania soczewki. Potem wyznacz y.",rozwiazanie:"1/y=1/10−1/30=1/15, więc y=15 cm."},
    {id:"OPT-02",typ:"zamkniete",poziom:3,pytanie:"Przedmiot znajduje się między ogniskiem a soczewką skupiającą. Jaki obraz powstaje?",odpowiedzi:{A: "Rzeczywisty, odwrócony i pomniejszony", B: "Rzeczywisty, prosty i powiększony", C: "Pozorny, odwrócony i pomniejszony", D: "Pozorny, prosty i powiększony"},poprawna:"D",wzor:"1/f=1/x+1/y",wskazowka:"Dla x<f wynik y z równania soczewki ma znak odpowiadający obrazowi pozornemu. Powiększenie jest większe od 1.",rozwiazanie:"Przy x<f soczewka skupiająca tworzy obraz pozorny, prosty i powiększony po tej samej stronie co przedmiot."},
    {id:"OPT-03",typ:"zamkniete",poziom:3,pytanie:"Promień przechodzi z powietrza do szkła o współczynniku załamania 1,5. Kąt padania wynosi 30°. Jaki jest w przybliżeniu kąt załamania?",odpowiedzi:{A: "48,6°", B: "15°", C: "19,5°", D: "30°"},poprawna:"C",wzor:"n₁sinα=n₂sinβ",wskazowka:"Dla powietrza przyjmij n≈1. Oblicz sinβ=sin30°/1,5, a następnie wyznacz kąt.",rozwiazanie:"sinβ=0,5/1,5=1/3, więc β≈19,5°."},
    {id:"OPT-04",typ:"zamkniete",poziom:3,pytanie:"Światło przechodzi ze szkła do powietrza. Jeśli kąt padania przekroczy kąt graniczny, wystąpi...",odpowiedzi:{A: "brak odbicia i brak załamania", B: "całkowite wewnętrzne odbicie", C: "dyfrakcja niezależnie od geometrii", D: "zwiększenie prędkości do zera"},poprawna:"B",wzor:"sinα_g=n₂/n₁",wskazowka:"Całkowite wewnętrzne odbicie wymaga przejścia z ośrodka optycznie gęstszego do rzadszego oraz kąta większego od granicznego.",rozwiazanie:"Dla szkła→powietrza po przekroczeniu kąta granicznego nie istnieje rzeczywisty kąt załamania, więc zachodzi całkowite wewnętrzne odbicie."},
    {id:"OPT-05",typ:"zamkniete",poziom:3,pytanie:"Dwie soczewki skupiające o ogniskowych 20 cm i 30 cm stykają się. Jaka jest ogniskowa układu?",odpowiedzi:{A: "12 cm", B: "50 cm", C: "10 cm", D: "25 cm"},poprawna:"A",wzor:"1/f=1/f₁+1/f₂",wskazowka:"Dla cienkich soczewek stykających się dodają się ich zdolności skupiające, czyli odwrotności ogniskowych.",rozwiazanie:"1/f=1/20+1/30=5/60=1/12, więc f=12 cm."},
    {id:"OPT-06",typ:"zamkniete",poziom:3,pytanie:"W doświadczeniu z siatką dyfrakcyjną maksima spełniają d sinθ=mλ. Jeśli długość fali wzrośnie przy stałym d i m, kąt θ...",odpowiedzi:{A: "zmaleje", B: "stanie się zawsze równy 90°", C: "wzrośnie", D: "pozostanie bez zmian"},poprawna:"C",wzor:"d sinθ=mλ",wskazowka:"Przy stałych d i m wzrost λ wymaga wzrostu sinθ.",rozwiazanie:"sinθ=mλ/d, więc wzrost λ powoduje wzrost θ, dopóki warunek jest fizycznie możliwy."},
    {id:"OPT-07",typ:"zamkniete",poziom:3,pytanie:"Dalekowidz używa soczewki skupiającej. Dlaczego?",odpowiedzi:{A: "Ponieważ oko dalekowidza jest całkowicie niewrażliwe na światło", B: "Ponieważ układ oka nie skupia promieni dostatecznie na siatkówce i potrzebuje zwiększenia zbieżności", C: "Ponieważ soczewka skupiająca zawsze zmniejsza moc optyczną oka", D: "Ponieważ obraz dalekowidza powstaje zawsze przed soczewką"},poprawna:"B",wzor:"P=1/f",wskazowka:"Korekcja ma przesunąć ognisko układu optycznego na siatkówkę. Dalekowzroczność oznacza niewystarczającą zdolność skupiającą.",rozwiazanie:"Soczewka skupiająca zwiększa zbieżność promieni, przesuwając ognisko w stronę siatkówki."},
    {id:"OPT-08",typ:"zamkniete",poziom:3,pytanie:"Światło o częstotliwości f przechodzi z próżni do szkła. Co dzieje się z jego częstotliwością i długością fali?",odpowiedzi:{A: "Częstotliwość rośnie, a długość fali maleje", B: "Częstotliwość maleje, a długość fali pozostaje stała", C: "Obie wielkości rosną", D: "Częstotliwość pozostaje stała, a długość fali maleje"},poprawna:"D",wzor:"v=λf",wskazowka:"Częstotliwość jest ustalana przez źródło i na granicy ośrodków pozostaje ciągła. W szkle prędkość jest mniejsza.",rozwiazanie:"f pozostaje stałe, a ponieważ v w szkle jest mniejsze, z v=λf wynika mniejsza długość fali."},
    {id:"OPT-09",typ:"otwarte",poziom:3,pytanie:"Soczewka ma ogniskową 20 cm. Przedmiot znajduje się 60 cm od niej. Oblicz odległość obrazu.",odpowiedzWzorcowa:"30 cm",poprawnaWartosc:30,tolerancja:0.005,jednostka:"cm",wymagaJednostki:true,slowaKluczowe:["30","cm"],wskazowka:"Użyj równania soczewki cienkiej i rozwiąż je względem odległości obrazu.",wzor:"1/f=1/x+1/y",rozwiazanie:"1/y=1/20−1/60=1/30, więc y=30 cm."},
    {id:"OPT-10",typ:"otwarte",poziom:3,pytanie:"Współczynnik załamania szkła wynosi 1,6. Oblicz prędkość światła w tym szkle, przyjmując c=3,0·10⁸ m/s.",odpowiedzWzorcowa:"1,875·10^8 m/s",poprawnaWartosc:1.875e+08,tolerancja:0.005,jednostka:"m/s",wymagaJednostki:true,slowaKluczowe:["1,875","10","m/s"],wskazowka:"Współczynnik załamania definiuje się jako n=c/v. Przekształć wzór względem v.",wzor:"n=c/v",rozwiazanie:"v=c/n=3,0·10⁸/1,6=1,875·10⁸ m/s."},
    {id:"OPT-11",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij, dlaczego po przejściu światła z powietrza do szkła promień załamany odchyla się ku normalnej.",odpowiedzWzorcowa:"W szkle światło porusza się wolniej, więc przy przejściu do ośrodka o większym współczynniku załamania kąt względem normalnej maleje.",slowaKluczowe:["wolniej","większy współczynnik","mniejszy kąt","normalnej"],wskazowka:"Odwołaj się do prawa Snelliusa i faktu, że n szkła jest większe niż n powietrza.",rozwiazanie:"n₁sinα=n₂sinβ. Gdy n₂>n₁, przy tym samym α musi być sinβ mniejsze, więc β<α. Promień ugina się ku normalnej."},
    {id:"OPT-12",typ:"otwarte",poziom:3,pytanie:"W doświadczeniu z dwiema szczelinami odległość między szczelinami zwiększono dwukrotnie. Opisz, jak zmieni się odległość między prążkami interferencyjnymi.",odpowiedzWzorcowa:"Zmniejszy się dwukrotnie.",slowaKluczowe:["zmniejszy","dwukrotnie"],wskazowka:"Skorzystaj z proporcjonalności Δx=λL/d.",wzor:"Δx=λL/d",rozwiazanie:"Przy stałych λ i L odległość prążków jest odwrotnie proporcjonalna do d. Podwojenie d zmniejsza Δx dwukrotnie."}
  ],
  elektromagnetyzm: [
    {id:"ELE-01",typ:"zamkniete",poziom:3,pytanie:"Oporniki 6 Ω i 3 Ω połączono równolegle i przyłożono napięcie 12 V. Jaki prąd pobiera cały układ?",odpowiedzi:{A: "6 A", B: "2 A", C: "4 A", D: "9 A"},poprawna:"A",wzor:"1/R=1/R₁+1/R₂, I=U/R",wskazowka:"Najpierw wyznacz opór zastępczy połączenia równoległego. Potem zastosuj prawo Ohma do całego układu.",rozwiazanie:"R_z=2 Ω. I=12/2=6 A."},
    {id:"ELE-02",typ:"zamkniete",poziom:3,pytanie:"Kondensator o pojemności 200 μF naładowano do napięcia 50 V. Ile energii jest w nim zgromadzone?",odpowiedzi:{A: "0,50 J", B: "250 J", C: "5,0 J", D: "0,25 J"},poprawna:"D",wzor:"E=1/2CU²",wskazowka:"Pamiętaj o zamianie mikrofaradów na farady. Energia rośnie z kwadratem napięcia.",rozwiazanie:"E=0,5·200·10⁻⁶·50²=0,25 J."},
    {id:"ELE-03",typ:"zamkniete",poziom:3,pytanie:"Przewodnik z prądem 4 A i długości 0,50 m jest prostopadły do pola magnetycznego 0,20 T. Jaka siła magnetyczna na niego działa?",odpowiedzi:{A: "2,5 N", B: "4,0 N", C: "0,40 N", D: "0,10 N"},poprawna:"C",wzor:"F=BIL",wskazowka:"Ponieważ przewodnik jest prostopadły do pola, sin90°=1. Wstaw trzy dane do wzoru.",rozwiazanie:"F=0,20·4·0,50=0,40 N."},
    {id:"ELE-04",typ:"zamkniete",poziom:3,pytanie:"Strumień magnetyczny przez zwojnicę zmienia się z 0,040 Wb do 0,010 Wb w czasie 0,020 s. Wartość średniej SEM indukcji wynosi...",odpowiedzi:{A: "2,0 V", B: "1,5 V", C: "0,75 V", D: "0,03 V"},poprawna:"B",wzor:"|ε|=|ΔΦ|/Δt",wskazowka:"Liczy się wartość bezwzględna zmiany strumienia podzielona przez czas.",rozwiazanie:"|ΔΦ|=0,030 Wb. ε=0,030/0,020=1,5 V."},
    {id:"ELE-05",typ:"zamkniete",poziom:3,pytanie:"W transformatorze idealnym liczba zwojów uzwojenia wtórnego jest czterokrotnie większa niż pierwotnego. Jeśli U₁=50 V, to U₂ wynosi...",odpowiedzi:{A: "200 V", B: "50 V", C: "400 V", D: "12,5 V"},poprawna:"A",wzor:"U₂/U₁=N₂/N₁",wskazowka:"Napięcia są proporcjonalne do liczby zwojów w transformatorze idealnym.",rozwiazanie:"U₂=50·4=200 V."},
    {id:"ELE-06",typ:"zamkniete",poziom:3,pytanie:"Elektron wlatuje z prędkością prostopadłą do jednorodnego pola magnetycznego. Jego tor będzie...",odpowiedzi:{A: "prostą w kierunku pola", B: "helisą z prędkością wzdłuż pola", C: "okręgiem", D: "parabolą"},poprawna:"C",wzor:"F=qvB",wskazowka:"Siła Lorentza jest prostopadła do prędkości i zmienia jej kierunek, nie wartość. To prowadzi do ruchu po okręgu.",rozwiazanie:"Dla v⊥B siła magnetyczna pełni rolę siły dośrodkowej, więc tor jest kołowy."},
    {id:"ELE-07",typ:"zamkniete",poziom:3,pytanie:"Jeśli napięcie na oporniku zwiększymy trzykrotnie przy stałym oporze, moc wydzielana na oporniku...",odpowiedzi:{A: "zmniejszy się trzykrotnie", B: "wzrośnie dziewięciokrotnie", C: "wzrośnie trzykrotnie", D: "nie zmieni się"},poprawna:"B",wzor:"P=U²/R",wskazowka:"Przy stałym R moc zależy od kwadratu napięcia, nie liniowo.",rozwiazanie:"P₂/P₁=(3U)²/U²=9."},
    {id:"ELE-08",typ:"zamkniete",poziom:3,pytanie:"Dwa punkty obwodu są połączone idealnym przewodem. W stanie ustalonym napięcie między nimi wynosi...",odpowiedzi:{A: "nieskończoność", B: "zawsze napięcie zasilacza", C: "wartość zależną od prądu niezależnie od oporu", D: "0 V"},poprawna:"D",wzor:"U=IR, R=0",wskazowka:"Idealny przewód ma opór równy zero. Z prawa Ohma wynika napięcie równe zeru mimo możliwego niezerowego prądu.",rozwiazanie:"U=I·0=0 V."},
    {id:"ELE-09",typ:"otwarte",poziom:3,pytanie:"Opornik 4 Ω i opornik 12 Ω są połączone równolegle do źródła 24 V. Oblicz całkowity prąd pobierany ze źródła.",odpowiedzWzorcowa:"8 A",poprawnaWartosc:8,tolerancja:0.005,jednostka:"A",wymagaJednostki:true,slowaKluczowe:["8","A"],wskazowka:"Możesz policzyć prądy w obu gałęziach i je dodać albo najpierw wyznaczyć opór zastępczy.",wzor:"1/R_z=1/R₁+1/R₂, I=U/R_z",rozwiazanie:"R_z=3 Ω. I=24/3=8 A."},
    {id:"ELE-10",typ:"otwarte",poziom:3,pytanie:"Przewodnik o długości 0,40 m porusza się z prędkością 5 m/s prostopadle do pola magnetycznego 0,30 T. Oblicz wartość siły elektromotorycznej indukowanej między jego końcami.",odpowiedzWzorcowa:"0,60 V",poprawnaWartosc:0.6,tolerancja:0.005,jednostka:"V",wymagaJednostki:true,slowaKluczowe:["0,60","V"],wskazowka:"Dla ruchomego przewodnika w opisanej geometrii użyj ε=Blv.",wzor:"ε=Blv",rozwiazanie:"ε=0,30·0,40·5=0,60 V."},
    {id:"ELE-11",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij, dlaczego zwiększenie napięcia na kondensatorze czterokrotnie powoduje szesnastokrotny wzrost zgromadzonej energii, jeśli pojemność pozostaje stała.",odpowiedzWzorcowa:"Ponieważ energia kondensatora jest proporcjonalna do kwadratu napięcia.",slowaKluczowe:["kwadratu","napięcia","16"],wskazowka:"Spójrz na potęgę napięcia we wzorze na energię kondensatora.",wzor:"E=1/2CU²",rozwiazanie:"E∝U². Po zmianie U→4U energia rośnie 4²=16 razy."},
    {id:"ELE-12",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij zgodnie z prawem Lenza, dlaczego prąd indukowany przeciwdziała zmianie strumienia magnetycznego, która go wywołała.",odpowiedzWzorcowa:"Kierunek prądu jest taki, aby wytworzone pole magnetyczne przeciwdziałało zmianie strumienia; jest to konsekwencja zasady zachowania energii.",slowaKluczowe:["przeciwdziała","zmianie","strumienia","energii"],wskazowka:"Nie chodzi o przeciwdziałanie samemu polu, lecz zmianie strumienia. Połącz prawo Lenza z zasadą zachowania energii.",wzor:"ε=−dΦ/dt",rozwiazanie:"Znak minus w prawie Faradaya-Lenza oznacza, że indukowany prąd wytwarza pole przeciwne zmianie strumienia. Dzięki temu nie powstaje energia z niczego."}
  ],
  mechanika_kwantowa_jadrowa: [
    {id:"KW-01",typ:"zamkniete",poziom:3,pytanie:"Foton ma częstotliwość 6,0·10¹⁴ Hz. Przyjmij h=6,63·10⁻³⁴ J·s. Jego energia wynosi około...",odpowiedzi:{A: "3,98·10⁻¹⁹ J", B: "1,11·10⁻⁴⁸ J", C: "3,98·10⁻²⁰ J", D: "9,05·10⁻¹⁹ J"},poprawna:"A",wzor:"E=hf",wskazowka:"Pomnóż częstotliwość przez stałą Plancka i pilnuj potęg dziesięciu.",rozwiazanie:"E=6,63·10⁻³⁴·6,0·10¹⁴≈3,98·10⁻¹⁹ J."},
    {id:"KW-02",typ:"zamkniete",poziom:3,pytanie:"Foton wybija elektron z metalu o pracy wyjścia 2,0 eV. Jeśli energia fotonu wynosi 5,0 eV, maksymalna energia kinetyczna elektronu wynosi...",odpowiedzi:{A: "2,5 eV", B: "7,0 eV", C: "10 eV", D: "3,0 eV"},poprawna:"D",wzor:"E_k,max=hf−W",wskazowka:"Energia fotonu jest dzielona na pracę wyjścia i maksymalną energię kinetyczną elektronu.",rozwiazanie:"E_k=5,0−2,0=3,0 eV."},
    {id:"KW-03",typ:"zamkniete",poziom:3,pytanie:"Próbka zawiera początkowo N₀ jąder. Po trzech okresach połowicznego rozpadu pozostanie...",odpowiedzi:{A: "N₀/6", B: "N₀/16", C: "N₀/8", D: "N₀/3"},poprawna:"C",wzor:"N=N₀/2ⁿ",wskazowka:"Po każdym okresie zostaje połowa aktualnej liczby jąder. Zastosuj ten proces trzy razy.",rozwiazanie:"N=N₀/2³=N₀/8."},
    {id:"KW-04",typ:"zamkniete",poziom:3,pytanie:"Elektron ma dwukrotnie większy pęd niż drugi elektron. Jak zmieni się jego długość fali de Broglie'a?",odpowiedzi:{A: "Zmniejszy się czterokrotnie", B: "Zmniejszy się dwukrotnie", C: "Wzrośnie dwukrotnie", D: "Nie zmieni się"},poprawna:"B",wzor:"λ=h/p",wskazowka:"Długość fali jest odwrotnie proporcjonalna do pędu.",rozwiazanie:"λ₂/λ₁=p₁/p₂=1/2."},
    {id:"KW-05",typ:"zamkniete",poziom:3,pytanie:"W atomie wodoru elektron przechodzi z poziomu o większej energii na poziom niższy. Co zachodzi?",odpowiedzi:{A: "Emisja fotonu o energii równej różnicy poziomów", B: "Zanik elektronu", C: "Wzrost energii całego atomu", D: "Absorpcja fotonu o dowolnej energii"},poprawna:"A",wzor:"hf=E_i−E_f",wskazowka:"Przejście na niższy poziom oznacza utratę energii przez atom, która musi zostać wyniesiona przez foton.",rozwiazanie:"Emitowany foton ma energię równą różnicy energii poziomów."},
    {id:"KW-06",typ:"zamkniete",poziom:3,pytanie:"W rozpadzie β⁻ neutron przechodzi w proton. Który zestaw cząstek jest emitowany w tym procesie?",odpowiedzi:{A: "pozyton i neutrino", B: "dwa elektrony", C: "elektron i antyneutrino elektronowe", D: "foton i proton"},poprawna:"C",wzor:"n→p+e⁻+ν̄_e",wskazowka:"Rozpad beta minus zwiększa liczbę protonów o jeden i zachowuje ładunek oraz liczby leptonowe dzięki antyneutrinie.",rozwiazanie:"n→p+e⁻+ν̄_e."},
    {id:"KW-07",typ:"zamkniete",poziom:3,pytanie:"Defekt masy jądra wiąże się z energią wiązania zgodnie z zależnością...",odpowiedzi:{A: "E=Δmc", B: "E=Δmc²", C: "E=Δm/c²", D: "E=Δm²c"},poprawna:"B",wzor:"E=Δmc²",wskazowka:"Różnica między sumą mas swobodnych nukleonów a masą jądra odpowiada energii wiązania przez równoważność masy i energii.",rozwiazanie:"E=Δmc²."},
    {id:"KW-08",typ:"zamkniete",poziom:3,pytanie:"Jeśli próbka promieniotwórcza ma aktywność początkową A₀, to po dwóch okresach połowicznego rozpadu aktywność wynosi...",odpowiedzi:{A: "2A₀", B: "A₀/2", C: "A₀/8", D: "A₀/4"},poprawna:"D",wzor:"A=A₀/2ⁿ",wskazowka:"Aktywność jest proporcjonalna do liczby nierozpadniętych jąder.",rozwiazanie:"A=A₀/2²=A₀/4."},
    {id:"KW-09",typ:"otwarte",poziom:3,pytanie:"Praca wyjścia metalu wynosi 2,2 eV. Foton ma energię 5,8 eV. Oblicz maksymalną energię kinetyczną wybitego elektronu.",odpowiedzWzorcowa:"3,6 eV",poprawnaWartosc:3.6,tolerancja:0.005,slowaKluczowe:["3,6","eV"],wskazowka:"Zastosuj równanie Einsteina dla efektu fotoelektrycznego i odejmij pracę wyjścia od energii fotonu.",wzor:"E_k,max=E_fot−W",rozwiazanie:"E_k,max=5,8−2,2=3,6 eV."},
    {id:"KW-10",typ:"otwarte",poziom:3,pytanie:"Okres połowicznego rozpadu izotopu wynosi 6 h. Jaka część początkowej liczby jąder pozostanie po 18 h?",odpowiedzWzorcowa:"1/8",poprawnaWartosc:1,tolerancja:0.005,slowaKluczowe:["1/8","osiem"],wskazowka:"18 h odpowiada trzem okresom połowicznego rozpadu.",wzor:"N=N₀/2ⁿ",rozwiazanie:"n=18/6=3, więc N/N₀=1/2³=1/8."},
    {id:"KW-11",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij, dlaczego zwiększenie częstotliwości światła powyżej częstotliwości progowej zwiększa maksymalną energię kinetyczną fotoelektronów, a nie tylko ich liczbę.",odpowiedzWzorcowa:"Energia pojedynczego fotonu rośnie wraz z częstotliwością, więc po odjęciu pracy wyjścia rośnie maksymalna energia kinetyczna elektronu.",slowaKluczowe:["energia fotonu","częstotliwość","pracy wyjścia","kinetycz"],wskazowka:"Zapisz E=hf i równanie Einsteina. Oddziel energię pojedynczego fotonu od natężenia wiązki.",wzor:"E_k,max=hf−W",rozwiazanie:"Większa częstotliwość oznacza większą energię każdego fotonu. Po pokonaniu pracy wyjścia nadwyżka trafia do energii kinetycznej elektronu."},
    {id:"KW-12",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij, dlaczego energia wiązania jądra jest związana z ubytkiem masy względem sumy mas swobodnych nukleonów.",odpowiedzWzorcowa:"Podczas związania układ traci energię; zgodnie z E=mc² odpowiada temu zmniejszenie masy układu o Δm.",slowaKluczowe:["energia","masa","E=mc","ubytek","wiązania"],wskazowka:"Połącz zasadę zachowania energii z równoważnością masy i energii.",wzor:"E_w=Δmc²",rozwiazanie:"Związane jądro ma mniejszą energię całkowitą niż rozdzielone nukleony. Różnica energii odpowiada defektowi masy przez E=Δmc² i jest energią wiązania."}
  ],
  teoria_wzglednosci: [
    {id:"WZ-01",typ:"zamkniete",poziom:3,pytanie:"Statek kosmiczny porusza się z v=0,80c. Współczynnik Lorentza γ wynosi około...",odpowiedzi:{A: "1,67", B: "1,25", C: "0,60", D: "2,00"},poprawna:"A",wzor:"γ=1/√(1−v²/c²)",wskazowka:"Podstaw v/c=0,80. Najpierw oblicz 1−0,8², potem pierwiastek i odwrotność.",rozwiazanie:"γ=1/√(1−0,64)=1/0,6≈1,67."},
    {id:"WZ-02",typ:"zamkniete",poziom:3,pytanie:"Zegar na pokładzie statku mierzy czas własny 3 h przy v=0,80c. Ile czasu minie w układzie Ziemi?",odpowiedzi:{A: "3,75 h", B: "1,8 h", C: "6 h", D: "5 h"},poprawna:"D",wzor:"Δt=γΔt₀",wskazowka:"Czas własny mierzony przez zegar poruszający się wraz z wydarzeniami jest krótszy niż czas współrzędny w układzie Ziemi.",rozwiazanie:"Δt=1,67·3 h≈5 h."},
    {id:"WZ-03",typ:"zamkniete",poziom:3,pytanie:"Pręt ma długość własną 10 m i porusza się wzdłuż swojej osi z v=0,60c. Jaką długość zmierzy obserwator w laboratorium?",odpowiedzi:{A: "6 m", B: "12,5 m", C: "8 m", D: "10 m"},poprawna:"C",wzor:"L=L₀/γ",wskazowka:"Dla 0,60c γ=1,25. Skrócenie dotyczy tylko wymiaru równoległego do ruchu.",rozwiazanie:"L=10/1,25=8 m."},
    {id:"WZ-04",typ:"zamkniete",poziom:3,pytanie:"Dwa statki lecą w tę samą stronę. W układzie Ziemi mają prędkości 0,80c i 0,60c. Jaką prędkość pierwszego zmierzy obserwator na drugim statku?",odpowiedzi:{A: "1,40c", B: "0,385c", C: "0,20c", D: "0,40c"},poprawna:"B",wzor:"u'=(u−v)/(1−uv/c²)",wskazowka:"Nie odejmuj klasycznie prędkości. Zastosuj relatywistyczne składanie prędkości.",rozwiazanie:"u'=(0,8−0,6)/(1−0,48)c=0,2/0,52c≈0,385c."},
    {id:"WZ-05",typ:"zamkniete",poziom:3,pytanie:"Która wielkość jest niezmiennikiem relatywistycznym w opisie pojedynczej cząstki?",odpowiedzi:{A: "Masa spoczynkowa", B: "Energia kinetyczna", C: "Długość poruszającego się pręta", D: "Prędkość mierzona w każdym układzie"},poprawna:"A",wzor:"m=const",wskazowka:"Wybierz wielkość, która nie zależy od wyboru inercjalnego układu odniesienia.",rozwiazanie:"Masa spoczynkowa jest niezmiennikiem; energia i pęd zależą od układu, podobnie jak długość wzdłuż ruchu."},
    {id:"WZ-06",typ:"zamkniete",poziom:3,pytanie:"Energia całkowita cząstki o masie spoczynkowej m i pędzie p spełnia zależność...",odpowiedzi:{A: "E=pc+m/c²", B: "E=mc+p", C: "E²=p²c²+m²c⁴", D: "E²=p²c²−m²c⁴"},poprawna:"C",wzor:"E²=p²c²+m²c⁴",wskazowka:"To relatywistyczna zależność łącząca energię, pęd i masę spoczynkową.",rozwiazanie:"E²=(pc)²+(mc²)²."},
    {id:"WZ-07",typ:"zamkniete",poziom:3,pytanie:"Dla prędkości v dużo mniejszej od c współczynnik γ jest bardzo bliski 1. Oznacza to, że...",odpowiedzi:{A: "ciało traci masę spoczynkową", B: "efekty relatywistyczne są małe i odzyskujemy przybliżenie klasyczne", C: "czas płynie wstecz", D: "prędkość światła zależy od obserwatora"},poprawna:"B",wzor:"γ≈1 dla v≪c",wskazowka:"Sprawdź granicę wzoru na γ dla małego v/c.",rozwiazanie:"Gdy v/c→0, γ→1, więc dylatacja i kontrakcja są zaniedbywalne."},
    {id:"WZ-08",typ:"zamkniete",poziom:3,pytanie:"Cząstka ma energię całkowitą dwukrotnie większą od swojej energii spoczynkowej. Co można powiedzieć o jej współczynniku γ?",odpowiedzi:{A: "γ=4", B: "γ=1/2", C: "γ=√2", D: "γ=2"},poprawna:"D",wzor:"E=γmc²",wskazowka:"Energia całkowita relatywistyczna jest równa γ razy energii spoczynkowej.",rozwiazanie:"E/E₀=γ, więc przy E=2E₀ mamy γ=2."},
    {id:"WZ-09",typ:"otwarte",poziom:3,pytanie:"Statek porusza się z v=0,60c. Oblicz współczynnik Lorentza γ.",odpowiedzWzorcowa:"1,25",poprawnaWartosc:1.25,tolerancja:0.005,slowaKluczowe:["1,25"],wskazowka:"Podstaw 0,60c do wzoru γ=1/√(1−v²/c²).",wzor:"γ=1/√(1−v²/c²)",rozwiazanie:"γ=1/√(1−0,36)=1/0,8=1,25."},
    {id:"WZ-10",typ:"otwarte",poziom:3,pytanie:"Zegar statku mierzy 4 h czasu własnego przy prędkości 0,60c. Oblicz czas zmierzony na Ziemi.",odpowiedzWzorcowa:"5 h",poprawnaWartosc:5,tolerancja:0.005,jednostka:"h",wymagaJednostki:true,slowaKluczowe:["5","h"],wskazowka:"Najpierw wyznacz γ=1,25, a potem zastosuj dylatację czasu.",wzor:"Δt=γΔt₀",rozwiazanie:"Δt=1,25·4 h=5 h."},
    {id:"WZ-11",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij, dlaczego żaden masywny obiekt nie może zostać przyspieszony do prędkości światła w próżni.",odpowiedzWzorcowa:"Gdy v zbliża się do c, γ rośnie bez ograniczeń, więc energia potrzebna do dalszego zwiększania prędkości również rośnie bez ograniczeń.",slowaKluczowe:["gamma","nieskończoność","energia","c","masywny"],wskazowka:"Rozważ granicę v→c we wzorze na γ i energię całkowitą.",wzor:"E=γmc²",rozwiazanie:"Dla v→c mianownik wzoru na γ dąży do zera, więc γ→∞. Dla m>0 energia całkowita potrzebna do osiągnięcia c byłaby nieskończona."},
    {id:"WZ-12",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij, dlaczego obserwator na Ziemi i astronauta mogą zmierzyć różne czasy między tymi samymi zdarzeniami, nie oznacza to jednak błędu pomiarowego.",odpowiedzWzorcowa:"Czas nie jest absolutny; różne układy inercjalne mogą przypisać zdarzeniom różne odstępy czasu, a poprawne pomiary łączy transformacja Lorentza.",slowaKluczowe:["czas","układ","względny","Lorentz","różne"],wskazowka:"Pomyśl o czasie własnym i dylatacji czasu. Różnica wynika z geometrii czasoprzestrzeni, nie z niedokładności zegarów.",wzor:"Δt=γΔt₀",rozwiazanie:"Czas własny i czas współrzędny nie są tym samym. Dla ruchu względnego zegary mogą wskazywać różne odstępy między zdarzeniami, zgodnie z transformacją Lorentza."}
  ],
  fizyka_materialow: [
    {id:"MAT-01",typ:"zamkniete",poziom:3,pytanie:"Pręt o długości 2,0 m wydłuża się o 1,0 mm pod wpływem siły osiowej. Jego przekrój ma 5,0 mm². Jeśli moduł Younga materiału wynosi 200 GPa, jaka siła działa na pręt?",odpowiedzi:{A: "500 N", B: "200 N", C: "1000 N", D: "50 N"},poprawna:"A",wzor:"σ=Eε, σ=F/A, ε=ΔL/L",wskazowka:"Najpierw policz odkształcenie względne ε=ΔL/L. Następnie naprężenie σ=Eε i na końcu F=σA.",rozwiazanie:"ε=0,001/2=5·10⁻⁴. σ=200·10⁹·5·10⁻⁴=10⁸ Pa. F=10⁸·5·10⁻⁶=500 N."},
    {id:"MAT-02",typ:"zamkniete",poziom:3,pytanie:"Pręt metalowy o długości 1,5 m ma współczynnik rozszerzalności liniowej 1,2·10⁻⁵ K⁻¹. O ile wydłuży się przy wzroście temperatury o 80 K?",odpowiedzi:{A: "0,144 mm", B: "14,4 mm", C: "0,0144 mm", D: "1,44 mm"},poprawna:"D",wzor:"ΔL=αLΔT",wskazowka:"Pomnóż trzy czynniki i pamiętaj, że wynik początkowo otrzymasz w metrach.",rozwiazanie:"ΔL=1,2·10⁻⁵·1,5·80=1,44·10⁻³ m=1,44 mm."},
    {id:"MAT-03",typ:"zamkniete",poziom:3,pytanie:"Dwa druty z tego samego materiału mają tę samą długość, ale drugi ma dwukrotnie większe pole przekroju. Przy tej samej sile rozciągającej naprężenie w drugim drucie jest...",odpowiedzi:{A: "takie samo", B: "czterokrotnie mniejsze", C: "dwukrotnie mniejsze", D: "dwukrotnie większe"},poprawna:"C",wzor:"σ=F/A",wskazowka:"Naprężenie jest ilorazem siły i pola przekroju. Zmień tylko A.",rozwiazanie:"Przy tym samym F podwojenie A zmniejsza σ dwukrotnie."},
    {id:"MAT-04",typ:"zamkniete",poziom:3,pytanie:"Materiał ma moduł Younga 70 GPa. Jeśli naprężenie wynosi 140 MPa, odkształcenie względne w zakresie sprężystym wynosi...",odpowiedzi:{A: "0,0002", B: "0,002", C: "0,02", D: "0,2"},poprawna:"B",wzor:"ε=σ/E",wskazowka:"Sprowadź MPa i GPa do zgodnych jednostek. 140 MPa = 0,14 GPa.",rozwiazanie:"ε=0,14/70=0,002."},
    {id:"MAT-05",typ:"zamkniete",poziom:3,pytanie:"W przewodniku opór elektryczny rośnie, gdy temperatura metalu wzrasta, ponieważ...",odpowiedzi:{A: "silniejsze drgania sieci zwiększają rozpraszanie elektronów", B: "ładunek elektronu rośnie", C: "przewodnik traci wszystkie atomy", D: "elektrony znikają z przewodnika"},poprawna:"A",wzor:"R=R₀[1+αΔT]",wskazowka:"Rozważ mikroskopowy mechanizm przewodnictwa w metalu i częstsze zderzenia elektronów z siecią.",rozwiazanie:"Wzrost temperatury zwiększa drgania sieci krystalicznej, co zwiększa rozpraszanie nośników i opór."},
    {id:"MAT-06",typ:"zamkniete",poziom:3,pytanie:"Materiał jest poddany naprężeniu poniżej granicy sprężystości. Po usunięciu obciążenia jego odkształcenie...",odpowiedzi:{A: "pozostaje zawsze takie samo", B: "zmienia znak", C: "zanika, a próbka wraca do pierwotnych wymiarów w modelu sprężystym", D: "rośnie bez ograniczeń"},poprawna:"C",wzor:"σ=Eε",wskazowka:"Granica sprężystości oddziela obszar, w którym deformacja jest odwracalna, od obszaru trwałych odkształceń.",rozwiazanie:"Poniżej granicy sprężystości deformacja jest odwracalna po zdjęciu obciążenia."},
    {id:"MAT-07",typ:"zamkniete",poziom:3,pytanie:"Dwa przewodniki z tego samego materiału i o tej samej długości mają pola przekroju A i 3A. Ich opory są w stosunku R₁:R₂ równym...",odpowiedzi:{A: "1:9", B: "3:1", C: "1:3", D: "9:1"},poprawna:"B",wzor:"R=ρL/A",wskazowka:"Opór jest odwrotnie proporcjonalny do pola przekroju. Większy przekrój oznacza mniejszy opór.",rozwiazanie:"R₁=ρL/A, R₂=ρL/(3A), więc R₁:R₂=3:1."},
    {id:"MAT-08",typ:"zamkniete",poziom:3,pytanie:"Wykres naprężenie–odkształcenie ma początkowo liniowy odcinek. Nachylenie tego odcinka odpowiada...",odpowiedzi:{A: "ciepłu właściwemu", B: "granicy plastyczności w każdej sytuacji", C: "gęstości materiału", D: "modułowi Younga"},poprawna:"D",wzor:"E=σ/ε",wskazowka:"W obszarze liniowym prawo Hooke'a dla rozciągania ma postać σ=Eε.",rozwiazanie:"Nachylenie σ(ε) wynosi E, czyli moduł Younga."},
    {id:"MAT-09",typ:"otwarte",poziom:3,pytanie:"Drut o długości 2,0 m wydłużył się o 0,50 mm. Oblicz odkształcenie względne ε.",odpowiedzWzorcowa:"2,5·10^-4",poprawnaWartosc:0.00025,tolerancja:0.005,slowaKluczowe:["2,5","10","-4"],wskazowka:"Odkształcenie względne jest ilorazem wydłużenia i długości początkowej. Sprowadź jednostki do metrów.",wzor:"ε=ΔL/L",rozwiazanie:"ε=0,00050/2,0=2,5·10⁻⁴."},
    {id:"MAT-10",typ:"otwarte",poziom:3,pytanie:"Pręt aluminiowy ma długość 2,0 m, a α=2,4·10⁻⁵ K⁻¹. O ile wydłuży się przy ogrzaniu o 50 K?",odpowiedzWzorcowa:"2,4 mm",poprawnaWartosc:2.4,tolerancja:0.005,jednostka:"mm",wymagaJednostki:true,slowaKluczowe:["2,4","mm"],wskazowka:"Zastosuj liniową rozszerzalność cieplną ΔL=αLΔT.",wzor:"ΔL=αLΔT",rozwiazanie:"ΔL=2,4·10⁻⁵·2,0·50=2,4·10⁻³ m=2,4 mm."},
    {id:"MAT-11",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij, dlaczego zwiększenie pola przekroju przewodnika zmniejsza jego opór, jeśli materiał i długość pozostają bez zmian.",odpowiedzWzorcowa:"Opór jest odwrotnie proporcjonalny do pola przekroju, ponieważ większy przekrój daje większy obszar przepływu ładunku.",slowaKluczowe:["odwrotnie","pole przekroju","opór","R=ρL/A"],wskazowka:"Skorzystaj z zależności na opór przewodnika i zinterpretuj fizycznie pole przekroju.",wzor:"R=ρL/A",rozwiazanie:"Przy stałych ρ i L zwiększenie A zmniejsza iloraz ρL/A. W modelu mikroskopowym większy przekrój daje więcej równoległych dróg przepływu nośników."},
    {id:"MAT-12",typ:"otwarte",poziom:3,pytanie:"Wyjaśnij różnicę między odkształceniem sprężystym a plastycznym na podstawie wykresu naprężenie–odkształcenie.",odpowiedzWzorcowa:"Odkształcenie sprężyste jest odwracalne po usunięciu obciążenia, a plastyczne pozostaje jako trwała deformacja po przekroczeniu zakresu sprężystości.",slowaKluczowe:["odwracalne","trwałe","sprężyste","plastyczne"],wskazowka:"Zwróć uwagę na to, co dzieje się z próbką po zdjęciu obciążenia.",wzor:"σ=Eε w zakresie sprężystym",rozwiazanie:"W obszarze sprężystym próbka wraca do wymiarów początkowych. Po przekroczeniu granicy sprężystości część odkształcenia pozostaje po odciążeniu."}
  ]
};

export { BANK_PYTAN_MATURALNYCH };